### PR TITLE
Add morsecode.csv

### PR DESCRIPTION
**Pull request by CryoSolace**

### CODE REVIEW

**Comment by monkeyboy2805** [comment]
Thanks for your contribution, we will review it soon

**Review by adampy — APPROVED** [review]
Hey, thank you for the addition. The addition looks good too me :)

**Comment by adampy** [comment]
@monkeyboy2805 is there anything you'd like changing with this? If not, I will merge and change the trivia.py on adambot so it can see this trivia (I will open this as an issue on main repo for me to fix shortly)

**Comment by raven0034** [comment]
> @monkeyboy2805 is there anything you'd like changing with this? If not, I will merge and change the `trivia.py` on adambot so it can see this trivia (I will open this as an issue on main repo for me to fix shortly)

sorry for not replying earlier but yeah lgtm as far as I can tell

**Pull request merged**
